In [ ]:
import pandas as pd
import json
from collections import defaultdict

In [2]:
import os
os.getcwd()

'c:\\Users\\SiddheshLihe\\Transformer-LLM-Training-Tuning-Reasoning\\Unsloth_Chatmodel'

In [3]:
df = pd.read_csv("../Data/tbl_user_chat_202610081150.csv")

In [4]:
df

,id,user_id,message,response,context,created_at,updated_at,session_id
0,353,50,hey,Hi Prachi! 😊 It's always nice to chat with you...,NaN,2025-12-08 11:14:39.577,2025-12-08 11:14:39.577,191
1,354,50,hi,Hi Prachi! 😊 It's great to hear from you again...,NaN,2025-12-08 11:14:57.581,2025-12-08 11:14:57.581,192
2,361,50,chicken sausage,Hi Prachi! I see you've logged chicken sausage...,"{""meal_log_id"": ""4170"", ""meal_log"": {""meal_typ...",2025-12-09 05:30:32.410,2025-12-09 05:30:32.410,198
3,365,50,How much protein do I need daily?,"To determine your daily protein needs, let's c...",NaN,2025-12-09 05:42:25.940,2025-12-09 05:42:25.940,202
4,367,50,What to eat before heavy workout?,"For a heavy workout, it's essential to fuel yo...",NaN,2025-12-09 05:45:48.050,2025-12-09 05:45:48.050,204
...,...,...,...,...,...,...,...,...
25819,25988,27742,abhi ma ra weight kit na ho gaa,Agar aap abhi 75 kg hain aur aapka goal 68 kg ...,NaN,2026-10-07 17:40:24.421,2026-10-07 17:40:24.421,13271
25820,25989,27742,kit na din Lenge,Agar aapka current weight 75 kg hai aur aapka ...,NaN,2026-10-07 17:41:25.377,2026-10-07 17:41:25.377,13271
25821,25990,18319,Snack Plate,It looks like you had a Snack Plate with some ...,"{""meal_log_id"": ""236525"", ""meal_log"": {""meal_t...",2026-10-08 02:22:20.877,2026-10-08 02:22:20.877,13272
25822,25991,26945,What to eat before heavy workout?,"Before a heavy workout, it’s great to fuel you...",NaN,2026-10-08 05:32:36.086,2026-10-08 05:32:36.086,13273
25823,25992,27768,what do I take for lunch,"For lunch, how about a **Vegetable Quinoa Bowl...",NaN,2026-10-08 05:51:33.177,2026-10-08 05:51:33.177,13274

In [10]:
df[df["message"].str.len() >=  2]

,id,user_id,message,response,context,created_at,updated_at,session_id
0,353,50,hey,Hi Prachi! 😊 It's always nice to chat with you...,NaN,2025-12-08 11:14:39.577,2025-12-08 11:14:39.577,191
1,354,50,hi,Hi Prachi! 😊 It's great to hear from you again...,NaN,2025-12-08 11:14:57.581,2025-12-08 11:14:57.581,192
2,361,50,chicken sausage,Hi Prachi! I see you've logged chicken sausage...,"{""meal_log_id"": ""4170"", ""meal_log"": {""meal_typ...",2025-12-09 05:30:32.410,2025-12-09 05:30:32.410,198
3,365,50,How much protein do I need daily?,"To determine your daily protein needs, let's c...",NaN,2025-12-09 05:42:25.940,2025-12-09 05:42:25.940,202
4,367,50,What to eat before heavy workout?,"For a heavy workout, it's essential to fuel yo...",NaN,2025-12-09 05:45:48.050,2025-12-09 05:45:48.050,204
...,...,...,...,...,...,...,...,...
25819,25988,27742,abhi ma ra weight kit na ho gaa,Agar aap abhi 75 kg hain aur aapka goal 68 kg ...,NaN,2026-10-07 17:40:24.421,2026-10-07 17:40:24.421,13271
25820,25989,27742,kit na din Lenge,Agar aapka current weight 75 kg hai aur aapka ...,NaN,2026-10-07 17:41:25.377,2026-10-07 17:41:25.377,13271
25821,25990,18319,Snack Plate,It looks like you had a Snack Plate with some ...,"{""meal_log_id"": ""236525"", ""meal_log"": {""meal_t...",2026-10-08 02:22:20.877,2026-10-08 02:22:20.877,13272
25822,25991,26945,What to eat before heavy workout?,"Before a heavy workout, it’s great to fuel you...",NaN,2026-10-08 05:32:36.086,2026-10-08 05:32:36.086,13273
25823,25992,27768,what do I take for lunch,"For lunch, how about a **Vegetable Quinoa Bowl...",NaN,2026-10-08 05:51:33.177,2026-10-08 05:51:33.177,13274

In [11]:
df = df.dropna(subset=["message", "response"])
df = df[df["message"].str.len() > 2]
df = df[df["response"].str.len() > 5]

In [14]:
# 3. Name cleaning function
import re


def clean_response(text):
    text = str(text)
    
    # Common patterns काढून टाक
    # Hi Name! / Hello Name! / Hey Name!
    text = re.sub(r"(Hi|Hello|Hey|Hii|Hiii)\s+[A-Za-z]+[!.,]?\s*", r"\1! ", text, flags=re.IGNORECASE)
    
    # Extra spaces साफ कर
    text = re.sub(r"\s+", " ", text).strip()
    
    return text

df["response_clean"] = df["response"].apply(clean_response)

In [15]:
df

,id,user_id,message,response,context,created_at,updated_at,session_id,response_clean
0,353,50,hey,Hi Prachi! 😊 It's always nice to chat with you...,NaN,2025-12-08 11:14:39.577,2025-12-08 11:14:39.577,191,Hi! 😊 It's always nice to chat with you. Are t...
2,361,50,chicken sausage,Hi Prachi! I see you've logged chicken sausage...,"{""meal_log_id"": ""4170"", ""meal_log"": {""meal_typ...",2025-12-09 05:30:32.410,2025-12-09 05:30:32.410,198,Hi! I see you've logged chicken sausage in you...
3,365,50,How much protein do I need daily?,"To determine your daily protein needs, let's c...",NaN,2025-12-09 05:42:25.940,2025-12-09 05:42:25.940,202,"To determine your daily protein needs, let's c..."
4,367,50,What to eat before heavy workout?,"For a heavy workout, it's essential to fuel yo...",NaN,2025-12-09 05:45:48.050,2025-12-09 05:45:48.050,204,"For a heavy workout, it's essential to fuel yo..."
5,372,430,how are you,I'm here and ready to help you with your healt...,NaN,2025-12-09 06:18:14.006,2025-12-09 06:18:14.006,153,I'm here and ready to help you with your healt...
...,...,...,...,...,...,...,...,...,...
25819,25988,27742,abhi ma ra weight kit na ho gaa,Agar aap abhi 75 kg hain aur aapka goal 68 kg ...,NaN,2026-10-07 17:40:24.421,2026-10-07 17:40:24.421,13271,Agar aap abhi 75 kg hain aur aapka goal 68 kg ...
25820,25989,27742,kit na din Lenge,Agar aapka current weight 75 kg hai aur aapka ...,NaN,2026-10-07 17:41:25.377,2026-10-07 17:41:25.377,13271,Agar aapka current weight 75 kg hai aur aapka ...
25821,25990,18319,Snack Plate,It looks like you had a Snack Plate with some ...,"{""meal_log_id"": ""236525"", ""meal_log"": {""meal_t...",2026-10-08 02:22:20.877,2026-10-08 02:22:20.877,13272,It looks like you had a Snack Plate with some ...
25822,25991,26945,What to eat before heavy workout?,"Before a heavy workout, it’s great to fuel you...",NaN,2026-10-08 05:32:36.086,2026-10-08 05:32:36.086,13273,"Before a heavy workout, it’s great to fuel you..."
25823,25992,27768,what do I take for lunch,"For lunch, how about a **Vegetable Quinoa Bowl...",NaN,2026-10-08 05:51:33.177,2026-10-08 05:51:33.177,13274,"For lunch, how about a **Vegetable Quinoa Bowl..."

In [18]:
# 4. Group by session
sessions = defaultdict(list)

for _, row in df.iterrows():
    sessions[row["session_id"]].append({
        "message": str(row["message"]).strip(),
        "response": row["response_clean"]
    })

In [19]:
# 5. Create ChatML format
training_data = []

system_prompt = """You are a friendly and knowledgeable Indian nutrition and fitness assistant. 
You give practical, easy-to-follow advice about food, protein, workouts, Indian meals, and healthy habits. 
Keep your replies warm, natural and helpful."""

In [20]:
for session_id, chats in sessions.items():
    messages = [{"role": "system", "content": system_prompt}]
    
    for chat in chats:
        messages.append({"role": "user", "content": chat["message"]})
        messages.append({"role": "assistant", "content": chat["response"]})
    
    if len(messages) >= 3:
        training_data.append({"messages": messages})

In [24]:
training_data[0:5]

[{'messages': [{'role': 'system',
    'content': 'You are a friendly and knowledgeable Indian nutrition and fitness assistant. \nYou give practical, easy-to-follow advice about food, protein, workouts, Indian meals, and healthy habits. \nKeep your replies warm, natural and helpful.'},
   {'role': 'user', 'content': 'hey'},
   {'role': 'assistant',
    'content': "Hi! 😊 It's always nice to chat with you. Are there any specific questions you have today about your meals or fitness routine? I'm here to help with anything you need on your journey to feeling healthier. How's everything going with your weight loss and daily routine? 🌿 Remember, this advice is tailored to your profile and goals."}]},
 {'messages': [{'role': 'system',
    'content': 'You are a friendly and knowledgeable Indian nutrition and fitness assistant. \nYou give practical, easy-to-follow advice about food, protein, workouts, Indian meals, and healthy habits. \nKeep your replies warm, natural and helpful.'},
   {'role': 'user', 'content': 'chicken sausage'},
   {'role': 'assistant',
    'content': "Hi! I see you've logged chicken sausage in your meal. While it's a tasty option, it might not align with your vegan dietary preference and weight loss goals. Let's explore some delicious vegan alternatives that can give you a similar savory experience while keeping you on track: 1. **Vegan Sausage**: Look for plant-based sausages available in markets. They! have flavors similar to traditional sausage but are made from ingredients like tofu, beans, or seitan. 2. **Spiced Tofu**: Marinate tofu cubes in your favorite spices and lightly grill them. This can be a flavorful and protein-rich alternative. 3. **Chickpea Patties**: Blend chickpeas with spices, form patties, and pan-fry for a crispy, satisfying meal. 4. **Lentil Loaf**: Use lentils combined with spices and bake it into a loaf for a hearty dish. 5. **Mushroom and Walnut Mix**: Sauté mushrooms with walnuts and spices for a savory topping or filling. These options not only align with your vegan preference but also provide varied nutrients that can support your weight loss journey. If you need more ideas or recipes, just let me know! 😊 How do these sound to you? Remember, this advice is tailored to your profile and goals."}]},
 {'messages': [{'role': 'system',
    'content': 'You are a friendly and knowledgeable Indian nutrition and fitness assistant. \nYou give practical, easy-to-follow advice about food, protein, workouts, Indian meals, and healthy habits. \nKeep your replies warm, natural and helpful.'},
   {'role': 'user', 'content': 'How much protein do I need daily?'},
   {'role': 'assistant',
    'content': "To determine your daily protein needs, let's consider your weight loss goal, activity level, and vegan diet. Generally, for weight loss and muscle maintenance, aiming for about 1.2 to 2.0 grams of protein per kilogram of body weight is recommended. Given your current weight of 173 kg, this would be approximately 207 to 346 grams of protein per day. However, your daily protein target of 321.10 grams seems quite high. Since your activity level is light, a moderate protein intake might be more suitable. You could aim for around 1.2 to 1.5 grams per kilogram, which would be approximately 207 to 260 grams daily. It’s important to ensure your protein sources are varied to cover essential amino acids, especially on a vegan diet. Here are some vegan-friendly protein sources: 1. **Legumes**: Lentils, chickpeas, and black beans are excellent choices. 2. **Tofu and Tempeh**: These soy-based options are versatile and protein-rich. 3. **Quinoa**: A complete protein that can be a great base for meals. 4. **Nuts and Seeds**: Almonds, chia seeds, and hemp seeds provide protein and healthy fats. 5. **Whole Grains**: Brown rice, millet, and buckwheat can contribute to your protein intake. 6. **Plant-Based Protein Powder**: Useful for supplementing your diet when needed. It’s important to balance protein with other macronutrients and not rely solely on supplements. If you’re considering adjusting your daily protein intake, it might be helpful to consult with a nutritionist for personalized advice. How do you feel about the current protein intake, and would you like help adjusting your diet plan to fit these guidelines? 😊 Remember, this advice is tailored to your profile and goals."}]},
 {'messages': [{'role': 'system',
    'content': 'You are a friendly and knowledgeable Indian nutrition and fitness assistant. \nYou give practical, easy-to-follow advice about food, protein, workouts, Indian meals, and healthy habits. \nKeep your replies warm, natural and helpful.'},
   {'role': 'user', 'content': 'What to eat before heavy workout?'},
   {'role': 'assistant',
    'content': "For a heavy workout, it's essential to fuel your body with the right nutrients to keep your energy levels up and support muscle function. Given your vegan lifestyle and goal of losing weight, here are some pre-workout meal ideas tailored just for you: 1. **Timing**: Aim to eat 1-3 hours before your workout to allow for digestion. This will give you the energy without feeling too full. 2. **Carbs for Energy**: Include a source of complex carbohydrates to provide sustained energy. Consider options like a banana with nut butter, a small bowl of oatmeal with fruit, or a whole grain toast with avocado. 3. **Protein for Muscle Support**: Pair your carbs with a moderate amount of protein to support muscle repair. Try a smoothie with plant-based protein powder, almond milk, and a handful of spinach. 4. **Healthy Fats**: Include a small amount of healthy fats to keep you satiated. A few nuts or seeds like chia or flaxseeds in your smoothie can do the trick. 5. **Hydration**: Ensure you're well-hydrated before starting. Drink water or a light herbal tea in the hours leading up to your workout. 6. **Sample Pre-Workout Snack**: A great option could be a slice of whole grain bread with almond butter and sliced banana, or a small quinoa salad with chickpeas and a squeeze of lemon. These snacks and meals can help you power through your workout while supporting your weight loss goals. How do these suggestions fit into your routine? If you need more ideas or adjustments, let me know! 😊 Remember, this advice is tailored to your profile and goals."}]},
 {'messages': [{'role': 'system',
    'content': 'You are a friendly and knowledgeable Indian nutrition and fitness assistant. \nYou give practical, easy-to-follow advice about food, protein, workouts, Indian meals, and healthy habits. \nKeep your replies warm, natural and helpful.'},
   {'role': 'user', 'content': 'how are you'},
   {'role': 'assistant',
    'content': "I'm here and ready to help you with your health and fitness journey! 😊 It sounds like you're making steady progress, which is fantastic. If there's anything specific on your mind regarding your diet, exercise, or any challenges you're facing, just let me know. Whether it's how to incorporate more protein into your meals or tips on staying motivated, I'm here to support you. Remember, this advice is tailored to your profile and goals."},
   {'role': 'user', 'content': 'hii'},
   {'role': 'assistant',
    'content': "Hey! 😊 It seems like you're doing a great job on your journey to feel healthier and reach your weight gain goal. If you have any new questions or need advice on your diet or fitness routine, feel free to share. I'm here to help you every step of the way! Remember, this advice is tailored to your profile and goals."},
   {'role': 'user', 'content': 'heyu'},
   {'role': 'assistant',
    'content': "Hey! 😊 It looks like you're making great progress on your journey to gain weight and feel healthier. If there's anything specific you'd like to discuss about your diet, exercise routine, or anything else related to your goals, just let me know. I'm here to help!"}]}]

In [23]:
with open("../Data/train_data.json", "w", encoding="utf-8") as f:
    json.dump(training_data, f, ensure_ascii=False, indent=2)

print(f"Total conversations: {len(training_data)}")
print("Saved as train_data.json")

Total conversations: 12882
Saved as train_data.json

In [25]:
with open("../Data/train_data_20samples.json", "w", encoding="utf-8") as f:
    json.dump(training_data[0:20], f, ensure_ascii=False, indent=2)

print(f"Total conversations: {len(training_data[0:20])}")
print("Saved as train_data_20samples.json")

Total conversations: 20
Saved as train_data_20samples.json